---
- name: Get progress marker
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    name: 005-apic-install-progress
    namespace: default
    api_key: "{{ login_token }}"
    host: "{{ cluster_api_url }}"
  register: existing_apic_install_progress

- name: Create CM marker if needed
  community.okd.k8s:
    state: present
    api_key: "{{ login_token }}"
    host: "{{ cluster_api_url }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: 005-apic-install-progress
        namespace: default
      data:
        state: started
  register: new_apic_install_progress
  when: (existing_apic_install_progress.resources | length) == 0

- name: Get marker CM state (existing marker)
  ansible.builtin.set_fact:
    apic_marker_state: "{{ existing_apic_install_progress.resources[0].data.state }}"
  when: (existing_apic_install_progress.resources | length) == 1

- name: Get marker CM state (new marker)
  ansible.builtin.set_fact:
    apic_marker_state: 'started'
  when: (existing_apic_install_progress.resources | length) == 0

- name: Skip apic-install task message
  debug:
    msg: "apic-install task already completed. Skipping ..."
  when: apic_marker_state == 'complete'

- name: Run apic-install tasks
  block:
    - name: Executing apic-install task message
      debug:
        msg: "Executing apic-install task"

    # - name: Set vars for Operator Group
    #   ansible.builtin.set_fact:
    #     operator_group_name: "{{ cp4i_apic.operator_group_name }}"
    #     operator_group_namespace:  "{{ cp4i_apic.namespace }}"

    # - name: OperatorGroup from template
    #   ansible.builtin.template:
    #     src: templates/cp4i-operator-group.yml.j2
    #     dest: k8s/cp4i-apic-operator-group.yml
    #     force: no

    # - name: OperatorGroup
    #   community.okd.k8s:
    #     state: present
    #     api_key: "{{ login_token }}"
    #     host: "{{ cluster_api_url }}"
    #     src: "k8s/cp4i-apic-operator-group.yml"

    - name: Subscription from template
      ansible.builtin.template:
        src: cp4i-apic-subscription.yml.j2
        dest: k8s/cp4i-apic-subscription.yml
        force: no

    - name: Subscription
      community.okd.k8s:
        state: present
        api_key: "{{ login_token }}"
        host: "{{ cluster_api_url }}"
        src: "k8s/cp4i-apic-subscription.yml"

    - name: Wait up to 3 mins for API Connect Subscription to be ready
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        name: "{{ cp4i_apic.subscription_name }}"
        namespace: "{{ cp4i_apic.subscription_namespace }}"
        api_key: "{{ login_token }}"
        host: "{{ cluster_api_url }}"
      register: apic_subscription
      until: apic_subscription.api_found and apic_subscription.resources is defined and (apic_subscription.resources | length) > 0 and apic_subscription.resources[0].status.currentCSV is defined
      delay: 10
      retries: 18

    - name: Wait up to 3 mins for DataPower GW Subscription to be ready
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        name: "{{ cp4i_apic.dpgw_subscription_name }}"
        namespace: "{{ cp4i_apic.dpgw_subscription_namespace }}"
        api_key: "{{ login_token }}"
        host: "{{ cluster_api_url }}"
      register: dpgw_subscription
      until: dpgw_subscription.api_found and dpgw_subscription.resources is defined and (dpgw_subscription.resources | length) > 0 and dpgw_subscription.resources[0].status.currentCSV is defined
      delay: 10
      retries: 18

    - name: Wait up to  5 mins for APIC Operator CSV to be avail
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        name: "{{ apic_subscription.resources[0].status.currentCSV }}"
        namespace: "{{ cp4i_apic.namespace }}"
        api_key: "{{ login_token }}"
        host: "{{ cluster_api_url }}"
      register: apic_csv
      until: apic_csv.resources is defined and (apic_csv.resources | length) == 1 and apic_csv.resources[0].status is defined and  apic_csv.resources[0].status.phase is defined and apic_csv.resources[0].status.phase == "Succeeded"
      delay: 10
      retries: 30

    - name: Wait up to 5 mins for DataPower GW Operator CSV to be avail
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        name: "{{ dpgw_subscription.resources[0].status.currentCSV }}"
        namespace: "{{ cp4i_apic.namespace }}"
        api_key: "{{ login_token }}"
        host: "{{ cluster_api_url }}"
      register: dpgw_csv
      until: dpgw_csv.resources is defined and (dpgw_csv.resources | length) == 1 and dpgw_csv.resources[0].status is defined and  dpgw_csv.resources[0].status.phase is defined and apic_csv.resources[0].status.phase == "Succeeded"
      delay: 10
      retries: 30

    - name: Wait a few seconds for APIC CR to be accessible
      ansible.builtin.pause:
        seconds: 10

    - name: APIConnectCluster from template
      ansible.builtin.template:
        src: cp4i-apic-cluster.yml.j2
        dest: k8s/cp4i-apic-cluster.yml
        force: no

    # Note need to retry this because initally you can get an error "failed calling webhook" when the APIC Operator is not ready
    - name: APIConnectCluster
      community.okd.k8s:
        state: present
        api_key: "{{ login_token }}"
        host: "{{ cluster_api_url }}"
        src: "k8s/cp4i-apic-cluster.yml"
      register: apic_cr
      until: apic_cr is not failed
      retries: 3
      delay: 20

  when: apic_marker_state == 'started'
