---
- name: Get progress marker
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    name: 002-pn-install-progress
    namespace: default
    api_key: "{{ login_token }}"
    host: "{{ cluster_api_url }}"
  register: existing_pn_install_progress

- name: Create CM marker if needed
  community.okd.k8s:
    state: present
    api_key: "{{ login_token }}"
    host: "{{ cluster_api_url }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: 002-pn-install-progress
        namespace: default
      data:
        state: started
  register: new_pn_install_progress
  when: (existing_pn_install_progress.resources | length) == 0

- name: Get marker CM state (existing marker)
  ansible.builtin.set_fact:
    pn_marker_state: "{{ existing_pn_install_progress.resources[0].data.state }}"
  when: (existing_pn_install_progress.resources | length) == 1

- name: Get marker CM state (new marker)
  ansible.builtin.set_fact:
    pn_marker_state: 'started'
  when: (existing_pn_install_progress.resources | length) == 0

- name: Skip pn-install task message
  debug:
    msg: "pn-install task already completed. Skipping ..."
  when: pn_marker_state == 'complete'

- name: Run pn-install tasks
  block:
    - name: Executing pn-install task message
      debug:
        msg: "Executing pn-install task"

    # - name: Set vars for Operator Group
    #   ansible.builtin.set_fact:
    #     operator_group_name: "{{ cp4i_pn.operator_group_name }}"
    #     operator_group_namespace:  "{{ cp4i_pn.namespace }}"

    # - name: OperatorGroup from template
    #   ansible.builtin.template:
    #     src: templates/cp4i-operator-group.yml.j2
    #     dest: k8s/cp4i-pn-operator-group.yml
    #     force: yes

    # - name: OperatorGroup
    #   community.okd.k8s:
    #     state: present
    #     api_key: "{{ login_token }}"
    #     host: "{{ cluster_api_url }}"
    #     src: "k8s/cp4i-pn-operator-group.yml"

    - name: Subscription from template
      ansible.builtin.template:
        src: cp4i-pn-subscription.yml.j2
        dest: k8s/cp4i-pn-subscription.yml
        force: no

    - name: Subscription 
      community.okd.k8s:
        state: present
        api_key: "{{ login_token }}"
        host: "{{ cluster_api_url }}"
        src: "k8s/cp4i-pn-subscription.yml"

    - name: Wait a few seconds for the  CSV to accessible
      ansible.builtin.pause:
        seconds: 5

    - name: Wait up to 3 mins for Subscription to be ready
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        name: "{{ cp4i_pn.subscription_name }}"
        namespace: "{{ cp4i_pn.subscription_namespace }}"
        api_key: "{{ login_token }}"
        host: "{{ cluster_api_url }}"
      register: pn_subscription
      until: pn_subscription.resources is defined and (pn_subscription.resources | length) > 0 and pn_subscription.resources[0].status.currentCSV is defined
      delay: 10
      retries: 18

    - name: Wait up to  5 mins for PN  Operator CSV to be avail
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        name: "{{ pn_subscription.resources[0].status.currentCSV }}"
        namespace: "{{ cp4i_pn.namespace }}"
        api_key: "{{ login_token }}"
        host: "{{ cluster_api_url }}"
      register: pn_csv
      until: pn_csv.resources is defined and (pn_csv.resources | length) == 1 and pn_csv.resources[0].status is defined and pn_csv.resources[0].status.phase is defined and  pn_csv.resources[0].status.phase == "Succeeded"
      delay: 10
      retries: 30

    - name: PlatformNavigator from template
      ansible.builtin.template:
        src: cp4i-platform-navigator.yml.j2
        dest: k8s/cp4i-platform-navigator.yml
        force: no

    - name: PlatformNavigator
      community.okd.k8s:
        state: present
        api_key: "{{ login_token }}"
        host: "{{ cluster_api_url }}"
        src: "k8s/cp4i-platform-navigator.yml"

  when: pn_marker_state == 'started'
