---
- name: test apic ready
  kubernetes.core.k8s_info:
    api_version: apiconnect.ibm.com/v1beta1
    kind: APIConnectCluster
    name: "{{ cp4i_apic.cr_name }}"
    namespace: "{{ cp4i_apic.namespace }}"
    api_key: "{{ login_token }}"
    host: "{{ cluster_api_url }}"
  register: apic_cr
  until: apic_cr.resources is defined and (apic_cr.resources | length) == 1 and apic_cr.resources[0].status is defined and (apic_cr.resources[0].status.conditions | selectattr('type','match','Ready') | selectattr('status','match','True') | list | length) > 0
  delay: 20
  retries: 1
